= Documentation checklist

Author: _{author}_

Are you done writing? Use the following checklist to polish your documentation:

* http://grammar.about.com/od/words/a/EnglishContractions.htm[Expand
contractions] to remove ambiguity and to increase non-native English
speakers' comprehension.

* **Spell-check** your document. If the content is sensitive
or confidential, do this offline.

* Make the **first letter** of the first word of each sentence
**uppercase**. For example, change _&quot;nanoc is a static
site generator, fit for building anything from a small personal blog to a large
corporate web site.&quot;_ to _&quot;Use nanoc&mdash;a
static-site generator&mdash;to build anything from a small personal blog to a
large corporate web site.&quot;_

* Use **unnumbered lists** for items, or tasks that can be
performed in a **any order**. Put the most important items at the
top of the list. Readers pay more attention to items at the top of a list.

* Use **numbered lists** for tasks that are to be performed
in a **particular order**.

* In headings and titles, **capitalize** the **first word** and
**proper nouns** such as someone's name.
http://www.quickanddirtytips.com/education/grammar/capitalizing-titles[Mignon
Fogarty (AKA Grammar Girl) lists this as style number three]. Because I do not
expect people to know what separable or inseparable phrasal verbs are, or
whether a preposition is used adjectively or adverbially, I do not recommend
style number one. _Sentence style_ is straightforward for non-writers.

Most importantly, be consistent.

'''
Last updated: {docdatetime}