= 20140215 ride report
Ursula Kallio <ursula.kallio@gmail.com>
v1.0
Author: _{author}_

I woke up tired and thinking, shit, I wish I could sleep a little while longer. I checked my phone and read Brian&rsquo;s bail-out email from 06.37. It gave me the motivation that I needed to get out of bed. I was already faster than the slowest one! (Somehow showing up this week made me feel redeemed for having bailed out the weekend prior.)

Ben, Tom, and Matt met up in Prenzlauer Berg to bike to Grunewald station rather than take the S-Bahn. Aubrey and I opted for the S-Bahn and happened to be in the same car on the way down. We chatted, she was riding to clear her head, and I sipped her coffee as I listened. We continued chatting. At Grunewald, the three others were at an easy-to-find station shop. As we rolled out, I was excited to be riding again. I sensed I was not the only one. The *temperature* was a comfortable *10&deg; C*, the wind was only somewhat noticeable, and the cloud coverage made it easy on the eyes. We rode.

I started to get hangry at, well, lunchtime. It is clearly the beginning of the training season (at least for me) because I was not carrying any food on me. As a person who has ridden from San Francisco to Los Angeles twice, this was uncharacteristic. I fed off others&rsquo; stashes throughout the day, including part of Aubrey&rsquo;s delicious Brie sandwich. That saved me on the ride, but it might have made Aubrey hungrier than she needed to be later on. This having-no-food business had me thinking that I could just *cook up hot dogs and stick them in my pockets*. It&rsquo;s the same shit you buy on the ride, so why not just prepare it ahead of them. *Matt* mentioned a *website for cooking your own biking food*.

Because I did not have enough real food to eat, I started considering a bail-out point. Ben noticed that I had grown tired. &ldquo;Just 5 more _miles_." (I speak to myself in American English.) We kept on and I used some of my http://www.aidslifecycle.org[ALC] training to move my mind where I needed it to go. Having enjoy several more kilometers of peaceful German countryside of farms and migrating birds overhead, https://lh3.googleusercontent.com/-uVAx5ORIHoQ/UwB-rZwpwpI/AAAAAAAAOEk/ImlNzpvhdM4/w886-h665/14%2B-%2B1[Aubrey&rsquo;s rear derailleur *suddenly causes her to stop*]. Her shock was understandable. Tom shouts, &ldquo;Mechanical!&rdquo; as he and I ride on to catch Matt who is concerned about baby duties and pushing the time away from home even further. We cycle back the short bit to share tools and offer moral support. Aubrey is quick to decide on the https://lh4.googleusercontent.com/-ozJ8G38DMyA/UwB_R6_D8QI/AAAAAAAAOFI/phPNZtV9bLA/w524-h698-no/14+[ideal chain length] for the https://plus.google.com/u/0/photos/yourphotos?pid=5980921080569579410&amp;oid=100268597725268324090[single-speed conversion]. This kind of shit just doesn&rsquo;t happen everyday so I am rather giddy at the opportunity to capture the scene of https://lh3.googleusercontent.com/-adEkp0pFvlY/UwCASZAkmeI/AAAAAAAAOGY/izRU1JfAqJk/w524-h698-no/14+[moral support] and https://lh3.googleusercontent.com/--XSzhJ8IkIc/UwCAmFzl_gI/AAAAAAAAOHA/OADQo5PUEaI/w931-h698-no/14+[teamwork]. The https://lh5.googleusercontent.com/-b05fvL3ahqk/UwCA5l1FqII/AAAAAAAAOHs/XR4nMKyRxOc/w524-h698-no/14+[final inspection] is complete and we take it slow for the rest of the ride. Aubrey has come down from her high of having a great bike and she grows &ldquo;ti[red] ti[red]&rdquo; for the rest of the ride. I leave my food troubles behind and focus on her. She starts to close her eyes to capture a bit of shut-eye. Been there, done that, get this grrrl some sugar. We keep her energized and hydrated for the remainder of the ride. My right knee is noticeably sore and I baby it because there is some sort of adjustment problem that I need to address. Surprisingly, no permanent damage all around to be had. We roll into the Brandenburg station for hot dogs, currywurst, pommes, und Bier.

Bis zum nexsten Wochenende!

'''
Last updated: {docdatetime}