= 2013 blog entries Ursula Kallio <ursula.kallio@gmail.com> v1.0 Author:
_{author}_

== 20131219 - Just two more minutes

It's 16.30 and I am in the middle of a public park called Parque del Retiro in
Madrid, Spain. There is a continuous stream of walkers, runners, and people
using public exercise equipment.

At the moment, I hear very little noise pollution. If I shift my focus, I hear
the birds and runners' shoes. The crunch of sand and the amount of oxygen
around me is very relaxing. This place is on the list of things to do be
tomorrow, again. There are skateboarders in the background, which means someone
is getting exercise.

Most of the leaves have fallen and some continue to fall. It's been a while
since I have experienced a proper fall. There is a quiet in the air that is
undisturbed by happiness oozers. A rain drop signals dinner time. Just two more
minutes, just two more minutes...

== 20131218 - Violin fingering hand

When I intensely studied violin, I was in touch with my hands physically and
figuratively. I would stretch my fingers to widen the spaces between my
fingers. My fingering hand has more spaced-apart fingers than my right hand.
It's been four days since I have been on my laptop for any decent length of
time. Somehow I miss typing away and it's slightly surprising. My fingers fly
around the keyboard and thoughts materialize virtually. This vacation is really
bringing me back to the basics. What fun to not take for granted, if only for a
few moments, that one can type on this electrical device ("box") and share
thoughts with the world rather instantaneously. I am glad that I remember what
it was like to not grow up with a computer.

== 20131218 - Nina Simone is having coffee with me

Hanging out with Nina Simone at <a
href="http://www.yelp.com/biz/toma-caf%C3%A9-madrid-2">Toma Café</a> in Madrid,
Spain is making my afternoon. Madrid is a city where you can find whatever you
want, but it's a noisy city in general. That said, it's possible to wander down
quiet streets and get away from the noise pollution. If you pass through
streets or alleys with street workers (AKA prostitutes), you can bypass the
noise pollution. I have opted to take their route for this reason. They are
even polite enough to ask me if I too am interested in their offerings. I smile
a good morning and keep moving as not to detract them from real money. I had
the idea of paying a couple for their time to interview them. Maybe I need to
be writing a book on the topic first: A, then B; not B, then A.

Traveling alone makes me realize that I am usually under internal (and
external) pressure to map the clock on the wall onto my body and internalize
it. How am I spending my itty bitty chunks of time. My brain and body say what
they need to say, the inanimate clock usually says something else. If I "waste"
a day, what does it matter? I still will have studied German once or twice any
given day. Today, I have already read in Spanish, researched eReaders,
downloaded free texts for testing purposes, and more. Only then have I had my
first cup of coffee.

== 20131213 - Gramma and Grampa's pensión 

Currently, I am in Madrid, Spain on holiday. I found a pleasant old couple to
room with at a pensión. The noise of the city is balanced by "Gramma" and
"Grampa". They are cheerful and have a glimmer in their eyes when they feel
like being social. Gramma shared two meatballs with me last night, which made
me feel comfortable. I had little desire to eat because I had been snacking
along my wandering way that day.

At the moment, I am missing the coffee-in-bed routine that we have going on;
Ben and I, not Gramma and/or Grampa and I. [LAUGHTER] Upon seeing where the
libraries are in town, I'll wander over to one after a cup or two of coffee.
While vacationing, people tend to have the urge to do do do, and libraries give
me a chance to be be be, or just be.

I have just downloaded a few free books to my account on
link:http://readmill.com[readmill.com]. DRM-free, baby. Check 'em out!

== 20131213 - Juna lakko Madridistä Toledoon

Olen Espanjassa istumassa junassa menossa Toledoon. Entinen juna ei lähtenyt
ajassa. Siis, ei lähtenyt ollenkaan, koska on lakko monta päivää koko päivällä.
Huomenna menen Segoviaan ja on mahdollista, että olen samassa tilanteessa.
Nukuin epärauhallisesti, koska olin hermostunut, että en voinut löytää
mistä minun on pakko ottaa junaan.

== 20130819 - A writer (@shanley) worth following

As a result of reading a FaceBook post by my friend Laurence, I wandered over
to read more of Shanley at
https://medium.com/about-work/65d4740f7a2f[https://medium.com/about-work/65d4740f7a2f].
Although she focuses on male bosses&mdash;notice the
http://www.imdb.com/title/tt0151804[image of two men] that she uses to
introduce her article&mdash;these types of learned behaviors can certainly be
executed by female bosses as well.

Wow does some of this ring very loudly in my ears. I had to look up the term
http://www.urbandictionary.com/define.php?term=gaslighting[gaslighting].  Even
just the knowing that there is a word for it makes me feel more sane.  

'''
Last updated: {docdatetime}
