= 2014 blog entries
Ursula Kallio <ursula.kallio@gmail.com>
v1.0
Author: _{author}_

== 20141103 Lifestyle changes

Since vacationing in Budapest and Serbia, I decided to change my lifestyle. Serbians eat _a lot_ of meat. After three days in Novi Sad, I was tempted to go vegan. Fortunately, that extreme feeling left after I ate green things. While in Budapest, I watched a https://www.youtube.com/watch?v=dBnniua6-oM[YouTube video called Sugar: The Bitter Truth], which was hauntingly powerful. The topic was familiar to me, but the discussion and diagrams about fructose digestion via the liver were new. As a result, I have eliminated sugar unless it is accompanied by natural fiber, such as a whole (small) orange rather than fresh-squeezed orange juice, and alcohol during the week from Sunday through Thursday. Initially, I tried a Monday through Friday schedule, but that proved to be too difficult given the natural tendency for people to socialize on Fridays and Saturdays. One caveat is that if I exercise intensely for more than one hour, I will take in sugar. However, that is corresponds directly with the activity level underway.

This week, I need to up my game and do more exercise. Now that I have changed my diet, my level of movement needs a boost. I have a subscription to http://dailyburn.com[Daily Burn] and will workout tonight. There, I said it. Now for the _doing_. I can choose to let myself down, or I can choose to follow through. One of my favorite trainers used the prompt, "Let's do something useful." That was such a non-threatening, motivating statement to hear. It is quite easy to be immediately more active. I biked to work today and will bike home too. That is a wonderful baseline, but I need more.

== 20140301 Digital house cleaning

It has been a long time (seven years) since I have owned `infobits.org`, and I now I own `infobits.eu`. Bit by bit, I am porting over content so I can more easily start from scratch with a new site. I am feeling kind of done with blog software Drupal or Wordpress.

'''
Last updated: {docdatetime}