= Blog 
Ursula Kallio <ursula.kallio@gmail.com>
v1.0
Author: _{author}_

== [[100-bücher-auf-deutsch,20160520]]20160520 - 100 Bücher auf Deutsch

Ich habe meine B2 Prüfung geschrieben am ende Mai. Ich habe die Schriftliche
Prüfung durchgefallen. Trotz spreche ich auf Niveau B2, mein Wortschatz ist
noch ziemlich klein. Deshalb möchte ich viel mehr extensiv auf Deutsch lesen.
Es gibt einige Regeln: kein Wörterbuch nutzen; das Niveau der Buch muss
einfach sein; immer steht ein Buch in der Toilette; kein Deadline für dieses
Projekt; einen kurzes Buch Bericht auf Deutsch über jedes Buch.

+++++++++++++++
<table>
  <tr>
    <th>Num</th>
    <th>Titel</th>
    <th>Autor(in)</th>
    <th>Sternen</th>
  </tr>
<!--   <tr>
    <td>000</td>
    <td>Zweimal ist einmal zuviel</td>
    <td>Janet Evanovich</td>
    <td>☆☆☆☆☆</td>
  </tr> 
  <tr>
    <td>000</td>
    <td>Die Leiden des jungen Werther — Band 1</td>
    <td>Johann Wolfgang von Goethe</td>
    <td>☆☆☆☆☆</td>
  </tr> 
  <tr>
    <td>000</td>
    <td>Todeslächeln, Band 1 — Verschleppt: Thriller</td>
    <td>Dorothé Kanders</td>
    <td>☆☆☆☆☆</td>
  </tr> -->
  <tr>
    <td>003</td>
    <td>Der Vorleser</td>
    <td>Bernhard Schlink</td>
    <td>☆☆☆☆☆</td>
  </tr>
  <tr>
    <td>002</td>
    <td>Ein Inspektor kommt</td>
    <td>J. B. Priestley</td>
    <td>★★★☆☆</td>
  </tr>
  <tr>
    <td>001</td>
    <td>Geheime Mission</td>
    <td>Hans J. König</td>
    <td>★★★☆☆</td>
  </tr>
</table>
+++++++++++++++

== [[20160321c,20160321c]]20160321c - Half of my VPN

Half of my VPN connection is set up. Gotta work on the rest of the setup a bit
later. 

== [[20160321b,20160321b]]20160321b - Use Signal

Thankfully, I am also using Signal for SMS messages over WiFi. I have removed
the SIM card from my phone because I made too many attempts to unlock the SIM
and blocked it.

When I unlock the SIM back in Berlin, I will remove the protection because it
only serves to annoy me thus far.

Another thing that I observed is that if I were in a situation where I needed
to send a "lost" email to my employer, I would not be able to due to the Great
Firewall. Will need to follow up with the security team about that observation
when I return home. To be clear, there is no need for me to contact them, and
this thought merely came to mind.

== [[20160321a,20160321a]]20160321a - In 北京 with limited Internet access

Access to the Internet is what it is in China. I have no direct access to
Google, GitHub, Instagram, Twitter, etc. This means that I cannot message
anyone directly via such means nor access redundant means of contact.
Therefore, here you go via Infobits. Also, I am using one hand to type so that
slows things down further. I have been taking images of food and can share more later.

Hello to all the friends whom I message on a regular basis.

Special thanks (again) to Denis for writing software that I can use to `ssh`
content under such restricted circumstances.