= English resources
Ursula Kallio <ursula.kallio@gmail.com>
v1.0
Author: _{author}_

== Online dictionaries

Look up words in http://dictionary.cambridge.org/dictionary/american-english/[American] English:

++++
<form action="http://dictionary.cambridge.org/search/american-english/direct/?utm_source=widget_searchbox_source&utm_medium=widget_searchbox&utm_campaign=widget_tracking" method="post">
<table style="font-size: 10px; border: 2px solid black; background: #242C72 url('http://dictionary.cambridge.org/external/images/sbr.gif?version=2014-10-16-1018') no-repeat top right;" width="150px" border="0" cellpadding="0" cellspacing="0">
<tbody>
<tr>
  <td colspan="2"><a href="http://dictionary.cambridge.org/" style="display:block; background: transparent url('http://dictionary.cambridge.org/external/images/sbl.gif?version=2014-10-16-1018') no-repeat 5px 6px; height: 32px;"></a>
  </td>
  </tr>
<tr>
 <td width="93px" style="padding: 4px 8px 4px 4px;"><input name="q" size="8" style="display:block; height: 100%;width: 100%; font-size:10px " type="text"/></td>
 <td width="7px" style="padding: 0px 4px 0px 0px;"><input width="100%" style="display:block; float: right; background: #92AE2E url('http://dictionary.cambridge.org/external/images/sbb.gif?version=2014-10-16-1018') repeat-x; border: 1px solid green; font-size:10px;" type="submit" border="0" value="&nbsp;&nbsp;&nbsp;&nbsp;"/>
 </td>
</tr>
</tbody>
</table>
</form>
++++

Look up words in http://dictionary.cambridge.org/dictionary/british/[British] English:

++++
<form action="http://dictionary.cambridge.org/search/british/direct/?utm_source=widget_searchbox_source&utm_medium=widget_searchbox&utm_campaign=widget_tracking" method="post">
<table style="font-size: 10px; border: 2px solid black; background: #242C72 url('http://dictionary.cambridge.org/external/images/sbr.gif?version=2014-10-16-1018') no-repeat top right;" width="150px" border="0" cellpadding="0" cellspacing="0">
<tbody>
	<tr>
		<td colspan="2"><a href="http://dictionary.cambridge.org/" style="display:block; background: transparent url('http://dictionary.cambridge.org/external/images/sbl.gif?version=2014-10-16-1018') no-repeat 5px 6px; height: 32px;"></a>
		</td>
	</tr>
	<tr>
		<td width="93px" style="padding: 4px 8px 4px 4px;"><input name="q" size="8" style="display:block; height: 100%;width: 100%; font-size:10px " type="text"/>
		</td>
		<td width="7px" style="padding: 0px 4px 0px 0px;"><input width="100%" style="display:block; float: right; background: #92AE2E url('http://dictionary.cambridge.org/external/images/sbb.gif?version=2014-10-16-1018') repeat-x; border: 1px solid green; font-size:10px;" type="submit" border="0" value="&nbsp;&nbsp;&nbsp;&nbsp;"/>
		</td>
	</tr>
	</tbody>
	</table>
</form>
++++

== Listening

Listen to a variety of sources while paying attention to regional dialects and
accents. Try listening to something three times: first, listen quickly; next,
listen at a relatively even speed compared to your current listening skills;
finally, listen more slowly than you need to.

== Speaking

Repeat questions that people ask you. Provide full-sentence responses. Learn
how to ask, "What is the a synonym for the word ___." Practice differentiating
between http://myweb.tiscali.co.uk/wordscape/wordlist/minimal.html[minimal pairs].

Note: If you are trying to http://rephrase.it[reduce your accent], avoid
practicing using speeches that are given to a very large audience such as a
presidential speech. Often, the speaker is trained to change some of the
voicing for the purpose of preserving his or her voice over a long period of
time.

== Reading

Aim to read material that you understand at a 90% rate or higher. This gives
you the best chance of guessing meaning from context. Without using a
dictionary, read a passage three times at different speeds: first, read as fast
as you can for one minute; next, slow down to read the same content for three
minutes; finally, slow down again to read the same content for five minutes.
Read all sorts of material; read advertisements, graffiti, newspapers, tram
tickets, magazines, and novels.

== Writing

* http://creativewritingprompts.com[Creative writing prompts]
* http://www.quickanddirtytips.com/grammar-girl[Grammar Girl: Quick and Dirty
	Tips]
* http://citationmachine.net[Citation Machine]
* http://thesaurus.com[Thesaurus]
* http://andromeda.rutgers.edu/~jlynch/Writing/index.html[Guide to Grammar and
	Style]
* http://owl.english.purdue.edu[OWL (**O**nline **W**riting **L**ab)]
* http://www.bartleby.com/141/index.html[Strunk and White]

== See also
* link:../documentation[Technical documentation]
* link:../documentation/style-guide[Infobits documentation style guide]
* http://ipa.typeit.org[Type IPA]
* http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/contents.htm[Glossary of linguistic terms]

'''
Last updated: {docdatetime}
