= Eine Zusammenfassung des Ausländerseins
Ursula Kallio <ursula.kallio@gmail.com>
v1.0
Author: _{author}_
Date: 20140320

Seit 10 [ins]#Monaten#[1] [del]#Monate# wohne ich in Berlin. Ich komme aus Kalifornien, aber bin ich in Minnesota geboren. Seit 20 [ins]#Jahren# [del]#Jarhe# habe ich [ins]#in anderen# [del]#im andere# Land leben wollen. [del]#Wenn habe# [ins]#Als# ich [ins]#nach# [del]#in# Berlin gezogen [ins]#bin#, [ins]#habe ich# [del]#ich habe# &bdquo;zu Hause&rdquo; gefühlt [ins]#innerhalb von# [del]#in# sechs Woche. Ich habe gefunden, dass ich bin &bdquo;zu Hause&rdquo; in Berlin sechs Woche nach ich gekommen habe als vier Jahre in San Francisco.

In Berlins Restaurants gibt es kein Druck^der^ schnell zu essen. Als möchten wir zahlen, kann ich der(die) Kellner(in), &bdquo;Könner wir zahlen?&rdquo; fragen.

Von eine negative Perspectiv finde ich dass die Deutschen korrigieren mich zu oft. Ich bekomme zu viele Meinungen über die Details des täglichen Lebens.

Denn habe ich blonde Haare und blauen Augen, es ist für mich einfacher als anderere Leute in Berlin oder Deutschland in das deutche Leben zu integrieren. Zum Beispiel, wenn gehe ich einkaufen, die Mehrheit der Menchen mit mir sofort Deutsch sprechen.

////
Als ich nach Berlin gezogen bin, habe ich mich innerhalb von sechs Wochen „zu Hause” gefühlt. Ich fand, dass ich in Berlin eher „zu Hause” bin, sechs Wochen, nachdem ich angekommen war, als nach vier Jahren in San Francisco.
In Berlins Restaurants gibt es keinen Druck, schnell zu essen. Wenn wir zahlen möchten, kann ich den(die) Kellner(in) fragen, „Können wir zahlen?”
Von einer negativen Perspektive finde ich, dass die Deutschen mich zu oft korrigieren. Ich bekomme zu viele Meinungen über die Details des täglichen Lebens.
Weil ich blonde Haare und blauen Augen habe, es ist für mich einfacher als für andere Leute, mich in Berlin oder Deutschland in das deutsche Leben zu integrieren. Zum Beispiel: Wenn ich einkaufen gehe, spricht die Mehrheit der Menschen mit mir sofort Deutsch.
////

[1] Seit nimmt Akkusativ.

'''
Last updated: {docdatetime}